spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jrtp
    password: root
    username: root
  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: update
    
server:
  port: 9090