server:
  port: 8080

spring:
  application:
    name: auth-service
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/Security_DB
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT Configuration
jwt:
  secret: your-256-bit-secret-key-here-make-it-long-and-secure
  expiration: 86400000 # 24 hours in milliseconds
  